In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv("../data/raw/household_data_15min_singleindex.csv")
df.head()

,utc_timestamp,cet_cest_timestamp,DE_KN_industrial1_grid_import,DE_KN_industrial1_pv_1,DE_KN_industrial1_pv_2,DE_KN_industrial2_grid_import,DE_KN_industrial2_pv,DE_KN_industrial2_storage_charge,DE_KN_industrial2_storage_decharge,DE_KN_industrial3_area_offices,...,DE_KN_residential5_refrigerator,DE_KN_residential5_washing_machine,DE_KN_residential6_circulation_pump,DE_KN_residential6_dishwasher,DE_KN_residential6_freezer,DE_KN_residential6_grid_export,DE_KN_residential6_grid_import,DE_KN_residential6_pv,DE_KN_residential6_washing_machine,interpolated
0,2014-12-11T17:45:00Z,2014-12-11T18:45:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-12-11T18:00:00Z,2014-12-11T19:00:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-12-11T18:15:00Z,2014-12-11T19:15:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014-12-11T18:30:00Z,2014-12-11T19:30:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-12-11T18:45:00Z,2014-12-11T19:45:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.shape
df.columns.tolist()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 153810 entries, 0 to 153809
Data columns (total 71 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   utc_timestamp                        153810 non-null  str
 1   cet_cest_timestamp                   153810 non-null  str
 2   DE_KN_industrial1_grid_import        65730 non-null   float64
 3   DE_KN_industrial1_pv_1               69151 non-null   float64
 4   DE_KN_industrial1_pv_2               69151 non-null   float64
 5   DE_KN_industrial2_grid_import        45113 non-null   float64
 6   DE_KN_industrial2_pv                 47998 non-null   float64
 7   DE_KN_industrial2_storage_charge     39010 non-null   float64
 8   DE_KN_industrial2_storage_decharge   39010 non-null   float64
 9   DE_KN_industrial3_area_offices       57437 non-null   float64
 10  DE_KN_industrial3_area_room_1        57437 non-null   float64
 11  DE_KN_industrial3_area_room_2        57437 non-null   float64
 12  DE_KN_industrial3_area_room_3        57440 non-null   float64
 13  DE_KN_industrial3_area_room_4        57440 non-null   float64
 14  DE_KN_industrial3_compressor         57437 non-null   float64
 15  DE_KN_industrial3_cooling_aggregate  57437 non-null   float64
 16  DE_KN_industrial3_cooling_pumps      57437 non-null   float64
 17  DE_KN_industrial3_dishwasher         57439 non-null   float64
 18  DE_KN_industrial3_ev                 41714 non-null   float64
 19  DE_KN_industrial3_grid_import        46036 non-null   float64
 20  DE_KN_industrial3_machine_1          57437 non-null   float64
 21  DE_KN_industrial3_machine_2          57437 non-null   float64
 22  DE_KN_industrial3_machine_3          57437 non-null   float64
 23  DE_KN_industrial3_machine_4          57440 non-null   float64
 24  DE_KN_industrial3_machine_5          57440 non-null   float64
 25  DE_KN_industrial3_pv_facade          57437 non-null   float64
 26  DE_KN_industrial3_pv_roof            57437 non-null   float64
 27  DE_KN_industrial3_refrigerator       56984 non-null   float64
 28  DE_KN_industrial3_ventilation        57437 non-null   float64
 29  DE_KN_public1_grid_import            18197 non-null   float64
 30  DE_KN_public2_grid_import            4491 non-null    float64
 31  DE_KN_residential1_dishwasher        63378 non-null   float64
 32  DE_KN_residential1_freezer           51580 non-null   float64
 33  DE_KN_residential1_grid_import       63487 non-null   float64
 34  DE_KN_residential1_heat_pump         63487 non-null   float64
 35  DE_KN_residential1_pv                63487 non-null   float64
 36  DE_KN_residential1_washing_machine   63381 non-null   float64
 37  DE_KN_residential2_circulation_pump  79291 non-null   float64
 38  DE_KN_residential2_dishwasher        76530 non-null   float64
 39  DE_KN_residential2_freezer           41000 non-null   float64
 40  DE_KN_residential2_grid_import       63190 non-null   float64
 41  DE_KN_residential2_washing_machine   98929 non-null   float64
 42  DE_KN_residential3_circulation_pump  132839 non-null  float64
 43  DE_KN_residential3_dishwasher        116384 non-null  float64
 44  DE_KN_residential3_freezer           114925 non-null  float64
 45  DE_KN_residential3_grid_export       90218 non-null   float64
 46  DE_KN_residential3_grid_import       47612 non-null   float64
 47  DE_KN_residential3_pv                90218 non-null   float64
 48  DE_KN_residential3_refrigerator      100400 non-null  float64
 49  DE_KN_residential3_washing_machine   122181 non-null  float64
 50  DE_KN_residential4_dishwasher        50477 non-null   float64
 51  DE_KN_residential4_ev                81148 non-null   float64
 52  DE_KN_residential4_freezer           81147 non-null   float64
 53  DE_KN_residential4_grid_export       81435 non-null   float64
 54  DE_KN_residential4_grid_import       81435 non-null   float64
 55  DE_KN_residential4_heat_pump         49239 non-null   float64
 56  DE_KN_residential4_pv                81435 non-null   float64
 57  DE_KN_residential4_refrigerator      43053 non-null   float64
 58  DE_KN_residential4_washing_machine   49028 non-null   float64
 59  DE_KN_residential5_dishwasher        94161 non-null   float64
 60  DE_KN_residential5_grid_import       123211 non-null  float64
 61  DE_KN_residential5_refrigerator      58254 non-null   float64
 62  DE_KN_residential5_washing_machine   94161 non-null   float64
 63  DE_KN_residential6_circulation_pump  86133 non-null   float64
 64  DE_KN_residential6_dishwasher        56243 non-null   float64
 65  DE_KN_residential6_freezer           61383 non-null   float64
 66  DE_KN_residential6_grid_export       66755 non-null   float64
 67  DE_KN_residential6_grid_import       86133 non-null   float64
 68  DE_KN_residential6_pv                86133 non-null   float64
 69  DE_KN_residential6_washing_machine   59136 non-null   float64
 70  interpolated                         121593 non-null  str
dtypes: float64(68), str(3)
memory usage: 83.3 MB

,DE_KN_industrial1_grid_import,DE_KN_industrial1_pv_1,DE_KN_industrial1_pv_2,DE_KN_industrial2_grid_import,DE_KN_industrial2_pv,DE_KN_industrial2_storage_charge,DE_KN_industrial2_storage_decharge,DE_KN_industrial3_area_offices,DE_KN_industrial3_area_room_1,DE_KN_industrial3_area_room_2,...,DE_KN_residential5_grid_import,DE_KN_residential5_refrigerator,DE_KN_residential5_washing_machine,DE_KN_residential6_circulation_pump,DE_KN_residential6_dishwasher,DE_KN_residential6_freezer,DE_KN_residential6_grid_export,DE_KN_residential6_grid_import,DE_KN_residential6_pv,DE_KN_residential6_washing_machine
count,65730.000000,69151.000000,69151.000000,45113.000000,47998.000000,39010.000000,39010.000000,57437.000000,57437.000000,57437.000000,...,123211.000000,58254.000000,94161.000000,86133.000000,56243.000000,61383.000000,66755.000000,86133.000000,86133.000000,59136.000000
mean,221554.089851,4520.320655,3545.186872,7996.226184,10728.677060,826.592343,503.721251,8489.951637,3148.657536,14652.301652,...,4690.002662,294.515130,244.463565,457.495175,45.881923,100.860781,2178.986341,4208.204466,10042.476028,38.227643
std,149026.587296,3287.170985,2536.251961,5129.061810,7625.527968,424.455449,254.398333,4601.592908,1769.127257,8195.769562,...,2612.395098,176.494473,129.832920,260.065445,28.797255,34.126776,1003.652603,1841.653780,6587.062609,21.898970
min,0.500000,0.020000,0.015000,0.329000,0.029000,0.000000,0.000000,2.738000,0.618000,2.055000,...,0.020000,0.000000,0.000000,0.034000,0.000000,0.005000,0.110000,1.010000,0.000000,0.000000
25%,77548.811000,1141.661500,853.954000,3677.433000,2502.448500,487.899250,304.219000,4674.052000,1556.158000,7684.926000,...,2254.466000,134.434000,141.409000,252.765000,18.464000,93.957000,1524.210000,3252.549000,3919.890000,22.275000
50%,224831.695500,5000.102000,3988.004000,6583.750000,10549.356000,920.858500,569.398000,8646.140000,3274.989000,14851.715000,...,4758.691000,300.326500,247.038000,447.303000,46.186000,104.914000,1760.510000,4555.864000,9563.700000,35.457000
75%,334317.734500,6694.052000,5183.133000,13206.473000,19012.817000,1116.520750,670.442250,12423.205000,4723.408000,21536.734000,...,7195.781500,447.719500,348.330000,669.106000,70.654000,127.344500,3347.620000,5406.044000,16670.075000,54.895000
max,511112.711000,11001.342000,8377.523000,16699.016000,22122.400000,1576.598000,954.553000,16046.565000,5981.095000,28679.348000,...,8773.800000,603.771000,476.462000,950.744000,96.078000,146.692000,3443.260000,7349.309000,20495.400000,78.641000

## Converting Timestamps to time objects

In [11]:
df["cet_cest_timestamp"] = pd.to_datetime(df["cet_cest_timestamp"], utc = True)
df = df.sort_values("cet_cest_timestamp")

In [12]:
df.isnull().sum().sort_values(ascending=False)

DE_KN_public2_grid_import              149319
DE_KN_public1_grid_import              135613
DE_KN_industrial2_storage_charge       114800
DE_KN_industrial2_storage_decharge     114800
DE_KN_residential2_freezer             112810
                                        ...
DE_KN_residential3_washing_machine      31629
DE_KN_residential5_grid_import          30599
DE_KN_residential3_circulation_pump     20971
utc_timestamp                               0
cet_cest_timestamp                          0
Length: 71, dtype: int64

## Focusing on residential 4 since it seems like it has the most prominent features for now

In [ ]:
res4_cols = [col for col in df.columns if col.startswith("DE_KN_residential4")]
res4 = df[["cet_cest_timestamp"] + res4_cols].copy()
res4 = res4.set_index("cet_cest_timestamp")
res4.index = res4.index.tz_convert("Europe/Berlin")
res4.index = res4.index.tz_localize(None)

Categorizing columns

In [18]:
grid_import = [c for c in res4_cols if "grid_import" in c]
pv = [c for c in res4_cols if "pv" in c]
devices = [c for c in res4_cols if c not in grid_import + pv and "grid_export" not in c]

In [20]:
res4.index.dtype

datetime64[us, UTC]